# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mew.Wrec
PackageVersion: 0.1.8
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: wrec.exe
  PortableCommandAlias: wrec
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/mewisme/wrec/releases/download/v0.1.8/wrec-v0.1.8-windows-amd64.zip
  InstallerSha256: 4B5E57FF1C24C5D49FB5D88A339CFA8D27600861023C1A7437DA8C256BBF1584
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-06-28
