# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Mew.Wrec
PackageVersion: 0.1.7
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: wrec.exe
  PortableCommandAlias: wrec
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/mewisme/wrec/releases/download/v0.1.7/wrec-v0.1.7-windows-amd64.zip
  InstallerSha256: C25FE033FB044AE5F497E444B78A054579AA856047CCB2F4E5093E312E6261E1
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-06-28
